In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model

In [2]:
df = pd.read_csv("C:/Users/hp/Documents/data/price_per_home.csv")
df.head()

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [3]:
dummies = pd.get_dummies(df.town)
dummies

monroe township  robbinsville  west windsor
0                 1             0             0
1                 1             0             0
2                 1             0             0
3                 1             0             0
4                 1             0             0
5                 0             0             1
6                 0             0             1
7                 0             0             1
8                 0             0             1
9                 0             1             0
10                0             1             0
11                0             1             0
12                0             1             0

In [4]:
df_merge = pd.concat([df, dummies], axis="columns")

In [5]:
df_merge.head()

town  area   price  monroe township  robbinsville  west windsor
0  monroe township  2600  550000                1             0             0
1  monroe township  3000  565000                1             0             0
2  monroe township  3200  610000                1             0             0
3  monroe township  3600  680000                1             0             0
4  monroe township  4000  725000                1             0             0

In [6]:
df_merge.drop(["town", "west windsor"], axis=1, inplace=True)

In [7]:
df_merge.head()

area   price  monroe township  robbinsville
0  2600  550000                1             0
1  3000  565000                1             0
2  3200  610000                1             0
3  3600  680000                1             0
4  4000  725000                1             0

In [8]:
x = df_merge.drop(["price"], axis=1)
x

area  monroe township  robbinsville
0   2600                1             0
1   3000                1             0
2   3200                1             0
3   3600                1             0
4   4000                1             0
5   2600                0             0
6   2800                0             0
7   3300                0             0
8   3600                0             0
9   2600                0             1
10  2900                0             1
11  3100                0             1
12  3600                0             1

In [9]:
y = df.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [12]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [13]:
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
model.score(x_test, y_test)

0.9794097209525928

## Making some prediction

### predicting home price in robbinsville

In [15]:
model.predict([[2800,0,1]])

array([590775.63964739])

### predicting home price in Monroe township

In [18]:
model.predict([[2800,1,0]])

array([565089.22812299])

## predicting home price in West windsor

In [19]:
model.predict([[2800,0,0]])

array([605103.20361213])

### The home price in west windsor is higher than the home price in monroe township and robbinswille  with the same square feet